language: cpp
os: linux
dist: bionic
compiler: gcc

matrix:
  include:
    - name: "Bionic GNU G++ (g++ 10.1.0)"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
      env:
        - TRAVIS_WORKER_DOCKER_CPUS=4
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - echo ${CC};
  - echo ${CXX};
  - ${CXX} --version;
  - cmake --version;

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_BUILD_TYPE=Debug ..
  - make clean && make -k
  - ctest -C Debug -V --output-on-failure